### ISSUE TITLE
Sch Job failure

### ISSUE THREAD

**Issue by petednz** [agileware/au.com.agileware.expiredcreditcards#2]
Finished execution of Find Expired Credit Cards with result: Failure, Error message: 'Credit Card Expired' is not a valid option for field activity_type_id

Has there been some change relating to activity_type_id v Name or Label of the Activity Type?

**Comment by agileware-justin** [comment]
Hi @petednz was fixed in 1.4.1 there was a couple of attempts to fix that issue, see https://github.com/agileware/au.com.agileware.expiredcreditcards/releases

Haven't seem the problem occur again, if you do let us know.
